---
- hosts: wiki
  tasks:
    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - apache2
        - apache2-mpm-event # Replaces slow mpm_prefork
        - php5
        - php5-intl # PHP i18n functions
        - php5-gd # PHP imaging library
        - php5-apcu # PHP caching
        - php5-mysql
        - php5-fpm # PHP fast process manager

    - name: activate apache modules
      command: a2enmod "{{ item }}"
      args:
        creates: "/etc/apache2/mods-enabled/{{ item }}.load"
      with_items:
        - rewrite # For short URLs
        - proxy
        - proxy_fcgi
      notify: restart apache

    - name: install apache config
      template:
        src: templates/wiki.conf
        dest: /etc/apache2/sites-available/wiki.conf
      notify: reload apache

    - name: activate apache config
      command: a2ensite wiki
      args:
        creates: /etc/apache2/sites-enabled/wiki.conf
      notify: reload apache

    - name: create wiki root
      file:
        path: /var/www/wiki
        state: directory
        owner: "{{ ansible_user }}"
        group: www-data

    - name: install wiki files
      unarchive:
        src: "https://releases.wikimedia.org/mediawiki/1.{{ mediawiki_major_version }}/\
          mediawiki-1.{{ mediawiki_major_version }}.{{ mediawiki_minor_version }}.tar.gz"
        dest: /var/www/wiki/
        extra_opts: [ '--strip-components=1' ]
        owner: "{{ ansible_user }}"
        group: www-data
        remote_src: true
        creates: /var/www/wiki/index.php

    - name: set permissions for image uploads
      file:
        path: /var/www/wiki/images/
        owner: www-data

    - debug:
        msg: >
          Installation complete. You may now follow the installation steps at http://{{ vhostname }}.
          For short URLs to work, make sure $wgArticlePath is set to '/{{ article_path_name }}/$1' in
          LocalSettings.php.

    - debug:
        msg: >
          Ensure that LocalSettings.php's permissions are set appropriately when you install it (it
          contains database connection credentials). It should be writable by the admin user and 
          readable by the webserver (www-data), but no one else.

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted

    - name: reload apache
      systemd:
        name: apache2
        state: reloaded
