---
- hosts: wiki
  tasks:
    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - apache2
        - apache2-mpm-event # Replaces slow mpm_prefork
        - php5
        - php5-intl # PHP i18n functions
        - php5-gd # PHP imaging library
        - php5-apcu # PHP caching
        - php5-mysql
        - php5-fpm # PHP fast process manager

    - name: activate apache modules
      command: a2enmod "{{ item }}"
      args:
        creates: "/etc/apache2/mods-enabled/{{ item }}.load"
      with_items:
        - rewrite # For short URLs
        - proxy
        - proxy_fcgi
      notify: restart apache

    - name: install apache config
      template:
        src: templates/wiki.conf
        dest: /etc/apache2/sites-available/wiki.conf
      notify: reload apache

    - name: activate apache config
      command: a2ensite wiki
      args:
        creates: /etc/apache2/sites-enabled/wiki.conf
      notify: reload apache

    - name: create wiki root
      file:
        path: "{{ install_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: www-data
        mode: 0750

    - name: install wiki files
      unarchive:
        src: "https://releases.wikimedia.org/mediawiki/1.{{ mediawiki_major_version }}/\
          mediawiki-1.{{ mediawiki_major_version }}.{{ mediawiki_minor_version }}.tar.gz"
        dest: "{{ install_path }}"
        extra_opts: [ '--strip-components=1' ]
        owner: "{{ ansible_user }}"
        group: www-data
        remote_src: true
        creates: "{{ install_path }}/index.php"

    - name: set permissions for image uploads
      file:
        path: "{{ install_path }}/images/"
        owner: www-data

    - name: create optional cache directory
      file:
        path: "{{ install_path }}/cache/"
        owner: www-data
        group: www-data
        state: directory

    - debug:
        msg: >
          Installation complete. You may now follow the installation steps at http://{{ vhostname }}.
          For short URLs to work, make sure $wgArticlePath is set to '/{{ article_path_name | default('wiki') }}/$1'
          in LocalSettings.php.

    - debug:
        msg: >
          Finally, an optional directory has been created for storing a file cache. If you want to
          use it, set $wgUseFileCache to true, and $wgFileCacheDirectory to '$IP/cache' in
          LocalSettings.php.

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted

    - name: reload apache
      systemd:
        name: apache2
        state: reloaded
